### ISSUE TITLE
Automatic scrolling through the driver list

### ISSUE THREAD

**Issue by MrPineMan** [ianperrin/MMM-Formula1#13]
I'm only showing the top 7 of the list in my mirror because showing all the drivers takes to much space.
Is it possible to add a function that scrolls slowly through the list and reset it back to the top when it reach the end?

**Comment by 73cirdan** [comment]
I did not look into this for the 2.0.0. version, but introduced an fan code for driver (or constructor).

"Whether to add the name of the driver to the driver standing list if it would fall out of the maxRowsDriver filter. "

Scrolling goes beyond my programming skills i'm afraid (im not sure if this can be achieved in the nunjucks template setup we use)

( We could build something that alernates between the first 10 and second 10 drivers, but this will become more complex than you think at first sight. Not eveyone wants to see 10 drivers, so the viewbox would vary.  We should consider viewbox size, and calculated the number of boxes to show. Also drivers are added during the season, )

I think we should close this issue as a won't do ?
