### ISSUE TITLE
Unable to load the module multiple times

### ISSUE THREAD

**Issue by SeLLeRoNe** [ianperrin/MMM-Formula1#17]
Hi,
I was trying to load the module twice to have Drivers and Constructures classifications but apparenlty it doesnt work.

I twould be nice if that could be fixed, or if type "BOTH" can be selected so to have both available.

Thanks :)
Best regards
Andrea

**Comment by AWSW2017** [comment]
Hello,
I would like to request the same as well. If selected “BOTH” would be nice to show them both at once or switch between the 2 tables at a set time of seconds.

Thanks a lot in advance. 😊

**Comment by 73cirdan** [comment]
In version 2.0.0. the option showStanding can be configured

DRIVER only show driver standing, 
CONSTRUCTOR only show constructor standing, 
BOTH show both driver and constructor standing, 
MIX alternate between driver and constructor standing (30s each), 
NONE do not show standing. The race schedule is shown.

I think we can close this issue ?

**Comment by AWSW-de** [comment]
Hi, 
totally forget that topic… Thanks a lot. =)

Yes, for sure. Works perfectly fine:

![IMG_0438](https://github.com/ianperrin/MMM-Formula1/assets/34800740/5985e27e-47b1-470e-89d8-ed22d72bf447)
