### ISSUE TITLE
Module not showing latest info

### ISSUE THREAD

**Issue by robmcc1983** [ianperrin/MMM-Formula1#20]
Hi,
Just want to say thanks for you module I love it, have used it this year and last :)
But at the moment it doesn't seem do be showing the correct standings since the last race.
I've never had this problem, usually I get up on a Monday morning at it's all updated but it appears not to at present.
Thanks
Rob

**Comment by ianperrin** [comment]
@robmcc1983 unfortunately it looks like the data used to display the standings hasn’t been updated to include the last race - http://ergast.com/api/f1/current/driverStandings

Until it gets updated, the module will be ‘out of date ’ 

Sorry about that.
