### ISSUE TITLE
Add translations for Season and Round in the footer

### ISSUE THREAD

**Issue by The-Exterminator** [ianperrin/MMM-Formula1#29]
The file templates/mmm-formula1-standings.njk
The [line](templates/mmm-formula1-standings.njk#L45) : 
```<td` class="xsmall align-right" colspan="5">Season: {{ season }}, Round: {{ round `}}</td>```
chanes to :
```<td class="xsmall align-right" colspan="5">{{ "SEASON" | translate }}: {{ season }}, {{ "ROUND" | translate }}: {{ round }}</td>```

Insert this to files in translations/de.json
`{
	"DRIVER": "Fahrer", "CONSTRUCTOR": "Konstrukteur", "SEASON": "Jahreszeit", "ROUND": "Runden"
}`

Insert this to files in translations/en.json
`{
	"DRIVER": "Driver", "CONSTRUCTOR": "Constructor", "SEASON": "Season", "ROUND": "Round"
}`

Insert this to files in translations/id.json (Do not know this country)
`{
	"DRIVER": "Pembalap", "CONSTRUCTOR": "Tim", "SEASON": "???", "ROUND": "???"
}`

Insert this to files in translations/nl.json
`{
	"DRIVER": "Bestuurder", "CONSTRUCTOR": "Constructeur", "SEASON": "Seizoen", "ROUND": "Ronde"
}`

Insert this to files in translations/sv.json
`{
	"DRIVER": "Förare", "CONSTRUCTOR": "Tillverkare", "SEASON": "Säsong", "ROUND": "Runda"
}`

Make this file to translations/da.json
and insert
`{
	"DRIVER": "Køre", "CONSTRUCTOR": "Konstruktør", "SEASON": "Sæson", "ROUND": "Runde"
}`

Insert this line to MMM-Formula1.js
`da: "translations/da.json",`

**Comment by ianperrin** [comment]
@The-Exterminator - thanks for the suggestions. These changes have now been included and should now be available if you update your module.
