### ISSUE TITLE
[Questions] IMSA WeatherTech

### ISSUE THREAD

**Issue by The-Exterminator** [ianperrin/MMM-Formula1#30]
Is there any possibility that you can make it for IMSA WeatherTech. ????

**Comment by ianperrin** [comment]
Hi @The-Exterminator - it might be possible. Do you know if there is an API to get the standings for the IMSA WeatherTech?

**Comment by The-Exterminator** [comment]
Hej @ianperrin No, i cant not find it, i hope you Can 🙆‍♂️

**Comment by The-Exterminator** [comment]
Hello @ianperrin.
I can only find the calendar file.
```
http://www.google.com/calendar/ical/njulhksvo83qeoruc3nhend9js%40group.calendar.google.com/public/basic.ics
```
So i hope you can fint the API to get the standings

**Comment by The-Exterminator** [comment]
@ianperrin 
Have you look on it yet ???
:-)

**Comment by ianperrin** [comment]
Sorry for the delay. This is not something I will be looking to incorporate in this module.
