### ISSUE TITLE
Error found: Error: Cannot find module 'f1-api'

### ISSUE THREAD

**Issue by JOLLY6R33NGIANT** [ianperrin/MMM-Formula1#34]
After installing the module when I go to use it I get the error: "Error found: Error: Cannot find module 'f1-api'" and a black screen with only the cursor visible.

**Comment by ianperrin** [comment]
@JOLLY6R33NGIANT 

thanks for raising the issue.

if you have recently installed (or updated) the MMM-Formula1 module, can you check you have installed the dependencies 

```

cd ~/MagicMirror/modules/MMM-Formula1
npm install --production
```
