### ISSUE TITLE
Request - Option to display FP1,FP2,FP3,Quali and race times in local time

### ISSUE THREAD

**Issue by OlivieraCarvalho** [ianperrin/MMM-Formula1#35]
It would be really cool if we could have an option to display session times as part of the calendar event listing in mirror local time

**Comment by The-Exterminator** [comment]
@OlivieraCarvalho 
You can set it [here](https://f1calendar.com/), from the F1 Site

1. Press on : "Add race dates & times to your Calendar"
2. Press on "Get calendar"
3. Copy the link from "For Google Calendar" and insert to you config/config.js file like
 "url: 'webcal://www.YOU LINK HER, REMEMBER NOT PASTE THE HTTPS://',"

**Comment by 73cirdan** [comment]
In version 2.0.0. if you set  showSchedule to true, you can see all the times for the next race, like FP, Qualiy and sprintrace times

I think we can close this issue ?
