### ISSUE TITLE
Add French

### ISSUE THREAD

**Issue by MisterTouch** [ianperrin/MMM-Formula1#41]
Hi,

I add a french version on my side, but I think you can add it on the module ;)

`
{
	"DRIVER": "Pilote",
	"CONSTRUCTOR": "Constructeur",
	"SEASON": "Saison",
	"ROUND": "Manche"
}
`

Have a nice day !

**Comment by ianperrin** [comment]
Thanks @MisterTouch I’ve added the French translations
