### ISSUE TITLE
Config not really working 

### ISSUE THREAD

**Issue by Niriuqq** [ianperrin/MMM-Formula1#43]
Hey
I have installed the module on my Magic Mirror but still have the following problems:
My config file of the modules looks like this:
![image](https://user-images.githubusercontent.com/113716635/209433187-c365c29a-dd5e-4d0a-82ed-49c2095d9e8b.png)
I want to have the normal F1 Driver Standings on the left side.
But without fade and without grayscale
On the right side I want to have the Constructor side, also without fade and without grayscale.
But when I start the Magic Mirror, this is what happens:
![image](https://user-images.githubusercontent.com/113716635/209433291-d8b814d2-8828-4a5f-8e9c-829ae68c2e9a.png)
Ignore the weather top right
Am I doing something wrong?
I have also not yet found out how to integrate the calendar into the Magic Mirror.
Thanks for help

**Comment by Niriuqq** [comment]
So I was able to fix the calendar but not the grayscale, Cunstuctor etc. yet.

**Comment by Niriuqq** [comment]
I was also able to solve the fade Problem by simply setting the FadePoint to 1.

**Comment by Niriuqq** [comment]
So I think you can only open the module once. 
Because if I delete one of the two, it works perfectly.

**Comment by Niriuqq** [comment]
Found the solution for the Fade and grayscale Problem.
Just remove the "" in the Config 
Like that:
config: {
                                grayscale: false,
                                calendar: true,
                                fade: false,
                                grayscale: false
                                                        // Optional configuration options - see https://github.com/ianperrin/MMM-Formula1#configuration-options
                        }

**Comment by Niriuqq** [comment]
So the current status is that everything works except for:
That I can also insert the Cunstructor Standings.
When both are running, one of them always does not work.
Any ideas?

**Comment by ianperrin** [comment]
Hi @Niriuqq 

glad you got the majority of things working. Unfortunately it is currently not possible to run two instances of the module :( 

there’s another issue logged to capture this ( #17 ) so if you’re okay, I’ll close this issue for now

**Comment by Niriuqq** [comment]
Ah okey shame.
Yes, the "ticket" can be closed.
