### ISSUE TITLE
update

### ISSUE THREAD

**Issue by firbird1562** [ianperrin/MMM-Formula1#45]
hoi.
when i try to update with git pull i get this error

error: Your local changes to the following files would be overwritten by merge: package-lock.json package.json Please commit your changes or stash them before you merge. Aborting

**Comment by ianperrin** [comment]
Hi @firbird1562 

no worries there is a simple fix for this.

First make sure you are in the directory for the module then run the following command `git reset --hard`

once that is done you should be able to pull the latest version

**Comment by firbird1562** [comment]
oke thanks
