### ISSUE TITLE
2023 Calendar

### ISSUE THREAD

**Issue by Niriuqq** [ianperrin/MMM-Formula1#46]
Hey 
Is the 2023 calendar online yet somehow?
Or how can I integrate / update it?

**Comment by Niriuqq** [comment]
I used another online calendar and it worked.
However, when will the 2023 standings be available?

**Comment by ianperrin** [comment]
@Niriuqq thanks for the questio.

The data displayed in the module is based on the information available from the API for the “current” season. Unfortunately, until the 2023 season actually starts, the API will treat the current season as 2022.

You can override this behaviour by explicitly setting the `season` option in the config

e.g.

```
  {
    module: "MMM-Formula1",
    position: "top_right",
    header: "F1 Standings",
    config: {
      season: 2023
    }
  },
```

Once the season starts, you can revert the option to current  (or remove it)

**Comment by Niriuqq** [comment]
Perfect.

That worked thanks.
