### ISSUE TITLE
Add Italian translation and coloured flags

### ISSUE THREAD

**Issue by mirrormonark** [ianperrin/MMM-Formula1#49]
Hello. I like this module. It would be possible to add 2 features. The first is the Italian translation. the second are the colored flags and insert that when approaching the date it turns red access (something similar to warn)

**Comment by mirrormonark** [comment]
Thank you for responding.

DRIVER - PILOTA (is better for F1)
CONSTRUCTOR - COSTRUTTORE
SEASON - STAGIONE
ROUND - ( i ask you what you mean, if you mean the lap number of the circuit.. has this name GIRO. if you mean the circuit is called CIRCUITO. if you mean the race number is called SESSIONE = this is Free practice, qualifying and race



for flags i mean for example: https://4.bp.blogspot.com/-dYZ5q5ytouo/WXTuXm-bzXI/AAAAAAAA_8k/oUfof7opzVYhO6feQI6Cjh1Ijw18QKHuACLcBGAs/s1600/world-country-flags-names.jpg

but maybe is better this https://thumbs.dreamstime.com/z/formula-1-flags-16145718.jpg

**Comment by ianperrin** [comment]
Thanks for the translations - they've been added to the module - please update to the latest version

**Comment by ianperrin** [comment]
Flags are already displayed in the drivers and constructors tables. By default, they are shown in grayscale. However if you set the `grayscale` option to false, they will display in colour. 

````
  {
    module: "MMM-Formula1",
    position: "top_right",
    header: "F1 Standings",
    config: {
      grayscale: false
    }
  }
````

Is this what you wanted?

**Comment by mirrormonark** [comment]
goodmorning, sir.
I just checked. For my personal taste I prefer flags with round style like this https://thumbs.dreamstime.com/z/formula-1-flags-16145718.jpg .. but even so it's fine.. I'm asking for something extra, aesthetic level.

**Comment by jonathanbonette** [comment]
i see that there are already some translations made, but how can I set a specific language to appear in my module?

**Comment by 73cirdan** [comment]
You can configure that for the entire mirror, see the first lines in the config files. Change the `language` parameter.
Instruction video here: https://m.youtube.com/watch?v=WPqO9Erq_hQ 
You probably need the value `it`

**Comment by 73cirdan** [comment]
closing, also added your pull request into devnov24 branch which will be merged into master soon
