### ISSUE TITLE
SIZE

### ISSUE THREAD

**Issue by mirrormonark** [ianperrin/MMM-Formula1#50]
sorry if I also insert this.. You may have the possibility to change the size of the module (small, medium, large). because it puts me very big.. if there is a way to change this. Thank you

**Comment by 73cirdan** [comment]
with the 2.0.0 version you have a lot of tweaks to influence the size of the module.

showStanding, 
maxRowsDriver, 
maxRowsConstructor, 
showSchedule,
showNextRace

I think we can close this issue ?
